from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from reciter_fetcher.catalog import build_catalog, serialize_catalog
from reciter_fetcher.curated import load_curated_reciters
from reciter_fetcher.storage import atomic_write_text


def _issue_key(issue: Any) -> tuple[str, str, int, str, str]:
    entry_id = issue.entry_id if issue.entry_id is not None else -1
    return (issue.file, issue.section or "", entry_id, issue.code, issue.message)


def _format_issue(issue: Any) -> str:
    location = f"{issue.file} {issue.section or '-'}"
    if issue.entry_id is not None:
        location += f" {issue.entry_id}"
    return f"{location}: {issue.code}: {issue.message}"


def build_candidate(root: Path) -> tuple[str | None, list[Any]]:
    reciters, parse_issues = load_curated_reciters(root)
    catalog, catalog_issues = build_catalog(reciters)
    issues = sorted([*parse_issues, *catalog_issues], key=_issue_key)
    return (None if issues else serialize_catalog(catalog)), issues


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the canonical catalog from curated Markdown")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="repository root")
    parser.add_argument("--check", action="store_true", help="check exact generated bytes without writing")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    source_directory = root / "data" / "curated" / "reciters"
    if not source_directory.is_dir():
        print(f"{source_directory}: curated reciter source directory is missing")
        return 1
    serialized, issues = build_candidate(root)
    if issues:
        for issue in issues:
            print(_format_issue(issue))
        return 1

    assert serialized is not None
    catalog_path = root / "data" / "curated" / "catalog.json"
    if args.check:
        try:
            current = catalog_path.read_bytes()
        except OSError as error:
            print(f"{catalog_path}: unable to read checked-in catalog: {error}")
            return 1
        if current != serialized.encode("utf-8"):
            print(f"{catalog_path}: generated catalog differs")
            return 1
        return 0

    atomic_write_text(catalog_path, serialized)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
